In [1]:
import numpy as np
import matplotlib.pyplot as plt
from numpy.core.fromnumeric import reshape
import pandas as pd
import datetime
import time
from sklearn import preprocessing

ROWCOUNT = 1
COLUMNCOUNT = 9

name = 'M1'
name2 = 'toplu'
name3 = "2008-2022"
#datas      = pd.read_csv('/content/drive/Othercomputers/2022 Masaüstü/Dersler 2022/Dersler-2021-2022-Donem-2/Lisans Projesi/EURUSD_'+name+'.csv', header=1)
datas      = pd.read_csv('C:/Users/ertad/Dersler 2022/Dersler-2021-2022-Donem-2/Lisans Github/EURUSD_'+name+'_'+name3+'.csv', header=1)

datas      = datas.values.tolist()
try :
    datas      = np.array([[i.split('\t') for i in k] for k in datas]).reshape(ROWCOUNT,COLUMNCOUNT)
except Exception as e:
    s = str(e).split()
row = int(int(s[5])/COLUMNCOUNT)

datas      = np.array([[i.split('\t') for i in k] for k in datas]).reshape(row,COLUMNCOUNT)

if COLUMNCOUNT ==8 :
    datas_df   = pd.DataFrame(datas,columns=['Date','Open','High','Low','Close','Tickvol','Vol','Spread'])
elif COLUMNCOUNT ==9:
    datas_df   = pd.DataFrame(datas,columns=['Date','Time','Open','High','Low','Close','Tickvol','Vol','Spread'])
datas_df

#import dill
#dill.dump_session(name+'_'+name2+'-ORJINAL-datas_df.db')

,Date,Time,Open,High,Low,Close,Tickvol,Vol,Spread
0,2008.12.29,00:03:00,1.40760,1.40760,1.40760,1.40760,1,0,20
1,2008.12.29,00:04:00,1.40740,1.40750,1.40740,1.40750,2,0,20
2,2008.12.29,00:05:00,1.40760,1.40810,1.40760,1.40800,7,0,20
3,2008.12.29,00:06:00,1.40810,1.40850,1.40790,1.40820,8,0,20
4,2008.12.29,00:07:00,1.40830,1.40970,1.40830,1.40920,13,0,20
...,...,...,...,...,...,...,...,...,...
4871851,2022.02.25,23:50:00,1.12726,1.12728,1.12714,1.12718,48,0,7
4871852,2022.02.25,23:51:00,1.12716,1.12720,1.12712,1.12712,19,0,10
4871853,2022.02.25,23:52:00,1.12716,1.12718,1.12713,1.12715,10,0,11
4871854,2022.02.25,23:53:00,1.12715,1.12728,1.12711,1.12725,22,0,7
4871855,2022.02.25,23:54:00,1.12726,1.12726,1.12714,1.12716,32,0,7

In [2]:
tmp =0
if 'Time' in datas_df.columns:
    tmp =pd.to_datetime(datas_df['Date']+" "+datas_df['Time'],format='%Y.%m.%d %H:%M:%S')
    datas_df = datas_df.drop('Time',axis=1)
else :
    tmp =pd.to_datetime(datas_df['Date'],format='%Y.%m.%d')
    
#datas_df = datas_df.drop(['Date'],axis=1)
datas_df = datas_df.drop(columns=['Vol'])
datas_df = datas_df.drop(columns=['Tickvol'])
datas_df = datas_df.drop(columns=['Spread'])
tmp

0         2008-12-29 00:03:00
1         2008-12-29 00:04:00
2         2008-12-29 00:05:00
3         2008-12-29 00:06:00
4         2008-12-29 00:07:00
                  ...
4871851   2022-02-25 23:50:00
4871852   2022-02-25 23:51:00
4871853   2022-02-25 23:52:00
4871854   2022-02-25 23:53:00
4871855   2022-02-25 23:54:00
Length: 4871856, dtype: datetime64[ns]

In [3]:
date2 = pd.DataFrame()
date2['Date'] = tmp
date = tmp
newDate = pd.DatetimeIndex(date)

n2 = pd.DataFrame()
m  = (2 * np.pi * newDate.month/12)
w  = (2 * np.pi * pd.Series(newDate).dt.isocalendar().week/(52.177457))
d  = (2 * np.pi * newDate.day/(365.242199))
h  = (2 * np.pi * newDate.hour/24)
mi = (2 * np.pi * newDate.minute/60)

n2['month_sin']  =  np.round(np.sin(m),5)
n2['month_cos']  =  np.round(np.cos(m),5)
n2['weekly_sin'] =  np.round(np.sin(w),5)
n2['weekly_cos'] =  np.round(np.cos(w),5)
n2['day_sin']   =  np.round(np.sin(d),5)
n2['day_cos']   =  np.round(np.cos(d),5)
n2['hour_sin']  =  np.round(np.sin(h),5)
n2['hour_cos']  =  np.round(np.cos(h),5)
n2['minute_sin'] = np.round(np.sin(mi),5)
n2['minute_cos'] = np.round(np.cos(mi),5)

n2['sin'] = n2['month_sin'] + n2['weekly_sin'] + n2['day_sin'] + n2['hour_sin'] + n2['minute_sin']
n2['cos'] = n2['month_cos'] + n2['weekly_cos'] + n2['day_cos'] + n2['hour_cos'] + n2['minute_cos']

datas_df = datas_df.drop(columns=['Date'])
#datas_df = datas_df.drop(columns=['Time'])

datas_df = pd.concat([
                      #date2['Date'],
                      datas_df,
                      n2['sin'],n2['cos'] 
                      ],axis=1)
datas_df

            Open     High      Low    Close      sin      cos
0        1.40760  1.40760  1.40760  1.40760  0.90759  4.82194
1        1.40740  1.40750  1.40740  1.40750  1.00531  4.78443
2        1.40760  1.40810  1.40760  1.40800  1.09857  4.73691
3        1.40810  1.40850  1.40790  1.40820  1.18636   4.6799
4        1.40830  1.40970  1.40830  1.40920   1.2677  4.61402
...          ...      ...      ...      ...      ...      ...
4871851  1.12726  1.12728  1.12714  1.12718  0.97922  3.44564
4871852  1.12716  1.12720  1.12712  1.12712  1.03623  3.53343
4871853  1.12716  1.12718  1.12713  1.12715  1.10211  3.61477
4871854  1.12715  1.12728  1.12711  1.12725  1.17612  3.68878
4871855  1.12726  1.12726  1.12714  1.12716  1.25746  3.75466

[4871856 rows x 6 columns]

In [5]:
#datas_df.to_csv("C:/Users/ertad/Dersler 2022/Dersler-2021-2022-Donem-2/Lisans Github/EURUSD_"+name+"_hazirVeri_"+name2+"_"+name3+"_dongulu.csv", columns =['Open','High','Low','Close',"month_sin","month_cos","weekly_sin","weekly_cos","day_sin","day_cos","hour_sin","hour_cos","minute_sin","minute_cos"])
datas_df.to_csv("C:/Users/ertad/Dersler 2022/Dersler-2021-2022-Donem-2/Lisans Github/EURUSD_"+name+"_hazirVeri_"+name2+"_"+name3+"_dongulu.csv", columns =['Open','High','Low','Close',"sin","cos"])
#datas_df.to_csv("/content/drive/Othercomputers/2022 Masaüstü/Dersler 2022/Dersler-2021-2022-Donem-2/Lisans Projesi/EURUSD_"+name+"_hazirVeri.csv", columns =['Open','High','Low','Close',"month_sin","month_cos","weekly_sin",'weekly_cos','day_sin','day_cos','hour_sin','hour_cos','minute_sin','minute_cos'])
#datas_df.to_csv("EURUSD_"+name+"_hazirVeri_"+name2+".csv", columns =['Date','Open','High','Low','Close'])